[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
regex = "1.4.2"
lalrpop-util = "0.19.1"

[build-dependencies]
lalrpop = { version = "0.19.1", features = ["lexer"] }